[theme]
base="light"
primaryColor="#0066ff"
backgroundColor="#ffffff"
secondaryBackgroundColor="#F0F2F6"
textColor="#011233"
font="sans serif"

[server]
port = 8686
enableStaticServing = true

[client]

toolbarMode = "minimal"
showErrorDetails = true